# docker-compose.yaml
version: "3"

networks:
  app-network:
    driver: bridge

volumes:
  mongo_vol:

services:
  web:
    image: sicemal/rotten-potatoes:v1
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 5000:5000
    environment:
      MONGODB_DB: "rottenpotatoes"
      MONGODB_HOST: "localhost"
      MONGODB_PORT: 27017
      MONGODB_USERNAME: "mongouser"
      MONGODB_PASSWORD: "mongopwd"
    networks:
      - app-network
    depends_on:
      - mongodb
    links:
      - mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongouser:mongopwd@mongodb:27017/admin"
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongouser"
      MONGO_INITDB_ROOT_PASSWORD: "mongopwd"
    ports:
      - 27017:27017
    volumes:
      - mongo_vol:/data/db
    networks:
      - app-network
